version: '3.9'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-global
    ports:
      - "${PGADMIN_PORT:-8000}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pgsql

  postgres:
    image: postgres:15
    container_name: postgres-global
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgsql

networks:
  pgsql:
    driver: bridge
volumes:
  pgadmin_data:
  postgres_data:
